apiVersion: apps/v1
kind: Deployment
metadata:
  name: ncrp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ncrp
  template:
    metadata:
      labels:
        app: ncrp
    spec:
      containers:
        - name: app
          image: 124704454835.dkr.ecr.us-west-2.amazonaws.com/ncrp:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: ncrp
spec:
  selector:
    app: ncrp
  ports:
    - port: 80
      targetPort: 8082
  type: ClusterIP
---
